### ISSUE TITLE
Error when running sample stock prediction code

### ISSUE THREAD

**Issue by flyingmeatball** [hmmlearn/hmmlearn#18] opened 2015-03-13 03:33 UTC
Hi everyone,
When running the sample code for the stock prediction (found here: https://github.com/hmmlearn/hmmlearn/blob/master/examples/plot_hmm_stock_analysis.py)

I got an the following error:
"ValueError: Rows of transmat must sum to 1.0"

After replacing the import with the old sklearn version the code worked perfectly for me.

replace
    `from hmmlearn.hmm import GaussianHMM`
with 
    `from sklearn.hmm import GaussianHMM`

Running on windows 7, 64 bit with python 2.7 and .15 sklearn release.  Is it me or is it the code?

Hope that helps!

**Comment by superbobry** [comment] 2015-03-13 07:47
Hello, do you get this error each time you run the example or does it appear randomly?

**Comment by flyingmeatball** [comment] 2015-03-13 13:14
It appears every time I run the code, are you able to reproduce the error?

**Comment by superbobry** [comment] 2015-03-13 19:31
Unfortunately I cant reproduce it. Can you post a full stacktrace of the error here?

**Comment by flyingmeatball** [comment] 2015-03-14 13:23
```python 
"""
==========================
Gaussian HMM of stock data
==========================
This script shows how to use Gaussian HMM.
It uses stock price data, which can be obtained from yahoo finance.
For more information on how to get stock prices with matplotlib, please refer
to date_demo1.py of matplotlib.
"""
 
from __future__ import print_function
 
import datetime
import numpy as np
import pylab as pl
from matplotlib.finance import quotes_historical_yahoo
from matplotlib.dates import YearLocator, MonthLocator, DateFormatter
from hmmlearn.hmm import GaussianHMM
 
 
print(__doc__)
 
###############################################################################
# Downloading the data
date1 = datetime.date(1995, 1, 1)  # start date
date2 = datetime.date(2012, 1, 6)  # end date
# get quotes from yahoo finance
quotes = quotes_historical_yahoo("INTC", date1, date2)
if len(quotes) == 0:
    raise SystemExit
 
# unpack quotes
dates = np.array([q[0] for q in quotes], dtype=int)
close_v = np.array([q[2] for q in quotes])
volume = np.array([q[5] for q in quotes])[1:]
 
# take diff of close value
# this makes len(diff) = len(close_t) - 1
# therefore, others quantity also need to be shifted
diff = close_v[1:] - close_v[:-1]
dates = dates[1:]
close_v = close_v[1:]
 
# pack diff and volume for training
X = np.column_stack([diff, volume])
 
###############################################################################
# Run Gaussian HMM
print("fitting to HMM and decoding ...", end='')
n_components = 5
 
# make an HMM instance and execute fit
model = GaussianHMM(n_components, covariance_type="diag", n_iter=1000)
 
model.fit([X])
 
# predict the optimal sequence of internal hidden state
hidden_states = model.predict(X)
 
print("done\n")
 
###############################################################################
# print trained parameters and plot
print("Transition matrix")
print(model.transmat_)
print()
 
print("means and vars of each hidden state")
for i in range(n_components):
    print("%dth hidden state" % i)
    print("mean = ", model.means_[i])
    print("var = ", np.diag(model.covars_[i]))
    print()
 
years = YearLocator()   # every year
months = MonthLocator()  # every month
yearsFmt = DateFormatter('%Y')
fig = pl.figure()
ax = fig.add_subplot(111)
 
for i in range(n_components):
    # use fancy indexing to plot data in each state
    idx = (hidden_states == i)
    ax.plot_date(dates[idx], close_v[idx], 'o', label="%dth hidden state" % i)
ax.legend()
 
# format the ticks
ax.xaxis.set_major_locator(years)
ax.xaxis.set_major_formatter(yearsFmt)
ax.xaxis.set_minor_locator(months)
ax.autoscale_view()
 
# format the coords message box
ax.fmt_xdata = DateFormatter('%Y-%m-%d')
ax.fmt_ydata = lambda x: '$%1.2f' % x
ax.grid(True)
 
fig.autofmt_xdate()
pl.show()

==========================
Gaussian HMM of stock data
==========================
This script shows how to use Gaussian HMM.
It uses stock price data, which can be obtained from yahoo finance.
For more information on how to get stock prices with matplotlib, please refer
to date_demo1.py of matplotlib.

fitting to HMM and decoding ...
C:\Python27\lib\site-packages\sklearn\utils\extmath.py:340: RuntimeWarning: invalid value encountered in subtract
  out = np.log(np.sum(np.exp(arr - vmax), axis=0))
C:\Python27\lib\site-packages\hmmlearn\base.py:532: RuntimeWarning: invalid value encountered in maximum
  np.maximum(self.transmat_prior - 1.0 + stats['trans'], 1e-20),
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-717dcb0488ed> in <module>()
     53 model = GaussianHMM(n_components, covariance_type="diag", n_iter=1000)
     54 
---> 55 model.fit([X])
     56 
     57 # predict the optimal sequence of internal hidden state

C:\Python27\lib\site-packages\hmmlearn\hmm.pyc in fit(self, obs)
    326         more training data, or increasing covars_prior.
    327         """
--> 328         return super(GaussianHMM, self).fit(obs)
    329 
    330 

C:\Python27\lib\site-packages\hmmlearn\base.pyc in fit(self, obs)
    391 
    392             # Maximization step
--> 393             self._do_mstep(stats, self.params)
    394 
    395         return self

C:\Python27\lib\site-packages\hmmlearn\hmm.pyc in _do_mstep(self, stats, params)
    246 
    247     def _do_mstep(self, stats, params):
--> 248         super(GaussianHMM, self)._do_mstep(stats, params)
    249 
    250         # Based on Huang, Acero, Hon, "Spoken Language Processing",

C:\Python27\lib\site-packages\hmmlearn\base.pyc in _do_mstep(self, stats, params)
    532                 np.maximum(self.transmat_prior - 1.0 + stats['trans'], 1e-20),
    533                 axis=1)
--> 534             self.transmat_ = transmat_

C:\Python27\lib\site-packages\hmmlearn\base.pyc in _set_transmat(self, transmat)
    449                              '(n_components, n_components)')
    450         if not np.all(np.allclose(np.sum(transmat, axis=1), 1.0)):
--> 451             raise ValueError('Rows of transmat must sum to 1.0')
    452 
    453         self._log_transmat = np.log(np.asarray(transmat).copy())

ValueError: Rows of transmat must sum to 1.0
```

**Comment by matthiasplappert** [comment] 2015-04-22 13:57
Any idea what might cause this? I'm currently running into the same problem (only sometimes) with custom training data. I've added some code to debug what's going on if the exception is raised. Concretely, I added `print np.sum(transmat, axis=1)` and `print transmat` before raising. Here's the result:

```
File "build/bdist.linux-x86_64/egg/hmmlearn/hmm.py", line 328, in fit
  File "build/bdist.linux-x86_64/egg/hmmlearn/base.py", line 411, in fit
  File "build/bdist.linux-x86_64/egg/hmmlearn/hmm.py", line 248, in _do_mstep
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]]
  File "build/bdist.linux-x86_64/egg/hmmlearn/base.py", line 554, in _do_mstep
  File "build/bdist.linux-x86_64/egg/hmmlearn/base.py", line 471, in _set_transmat
ValueError: Rows of transmat must sum to 1.0
```

Apparently every single entry in `transmat` is `nan`. Any idea what could cause this?

**Comment by superbobry** [comment] 2015-04-22 15:04
@matthiasplappert can you link me to the data which led to nans? In general nans are tricky to track down, because they could be anywhere :)

I've tried running stock prediction multiple times locally and couldn't reproduce the `ValueError`.

**Comment by matthiasplappert** [comment] 2015-04-23 06:27
I'll provide a test case for this on Monday or Tuesday. I didn't run into it with the stock example but rather with my own dataset. It's also worth noting that this only happens for certain subsets, so I believe this might be a numerical problem. Anyway, I'll post here again as soon as I have an isolated test case.

**Comment by matthiasplappert** [comment] 2015-04-27 10:52
I just tried to reproduce this again with the latest version (https://github.com/hmmlearn/hmmlearn/commit/acbd62fe9bff5deecd6517ed9db7377c92dd7a7d) and this appears to be fixed now. If I ever encounter this again, I'll post here again.

**Closed** 2015-04-27 10:53 UTC
