### ISSUE TITLE
Why do I get “'diag' mixture covars must be non-negative” error when I use model.score in hmmlearn?

### ISSUE THREAD

**Issue by AliEsmailpor** [hmmlearn/hmmlearn#352] opened 2019-08-01 09:42 UTC
I've been working on continues speech recognition for a month and I found `hmmlearn` package. I could create my phoneme models with `_model = hmm.GMMHMM(...)` and `_model.fit(...)`. But when I want to use <i>_model.score(_extracted_test_features)<i> for test samples, I got this error:

> .format(self.covariance_type)) ValueError: 'diag' mixture covars must
> be non-negative

Here is my code:

        def Main():
            # ---
            _phoneme_files_dir = './database_info/phonemes/phoneme_files/'
            _phoneme_dataset_dir = './database_info/phonemes/extracted_features/'
            _phoneme_models_dir = './database_info/phonemes/models/'
            _phoneme_test = '/home/ali/speech_recognition/database/database_english/timit/data/lisa/data/timit/raw/TIMIT/TEST/DR1/FAKS0/SA1.wav'
            # ---
            _phoneme_test_features = ExtractFeatures(_phoneme_test, 9640, 11240)
            _phoneme_models, _phoneme_models_list_loaded = LoadModels(_phoneme_models_dir)
            print("Getting models has successfully done")
            # ---
            _score_list = {}
            for _model_label in _phoneme_models.keys():
                _model = _phoneme_models[_model_label][0]
                _score = _model.score(_phoneme_test_features)
                _score_list[_model_label] = _score
            _predict = max(_score_list, key=_score_list.get)
            print("predict result phoneme is ", _phoneme_models_list_loaded[_predict])

Anyone knows about this error?

**Comment by AliEsmailpor** [comment] 2019-08-04 05:55
It means I have to change my library? I'm disappointed. @superbobry  Can you help me?

**Comment by Bingo-W** [comment] 2019-08-05 03:36
I get the same problem. Do anyone have some solution?

**Comment by AliEsmailpor** [comment] 2019-08-05 05:59
Dear Bingo-W, probably we should work on it.
What did you do? Can I see your code?

**Comment by Bingo-W** [comment] 2019-08-05 06:12
Maybe the reason is the input. If the length of the input is too small, one of the normal distribution will get one sample after the initialization with k-means. And then this distribution will get the means with zero covariance. This is some of my thought. But I have not to verify.

**Comment by AliEsmailpor** [comment] 2019-08-05 06:26
What do you mean about 'input'? You mean Features???
Your problem is in train level or test level? Which function?
I think the functions can handle what you said. I'm not sure. But I'll check it.

**Comment by Bingo-W** [comment] 2019-08-05 06:39
You can see what the error is. If you try to decode or score the test data, the model will check it parameter, which is not check after the fit action. So I think maybe the problem is training not testing. I suggest you can see where the code print the error in hmmlearn.
![image](https://user-images.githubusercontent.com/32786550/62443947-cdf2ef00-b78e-11e9-816c-d389206bb359.png)

**Comment by Bingo-W** [comment] 2019-08-05 09:12
I have solved my problem! 
The reason is that one of my input is awful. It has zero covariance in one of its dimensionality. Because we choose the diag as the model type(in the model initialization), the covariance is equal to its variance. If your train data has the same features, you will get the error. I try to filter my train data before fit action, and then avoid the error. 
I hope my suggestion is helpful to you.

**Comment by AliEsmailpor** [comment] 2019-08-05 11:38
Thank you for your suggestion.
I'll work on it.
But why two features should be same? Definitely we can't find any two recorded voice as like as each other.

**Comment by anntzer** [comment] 2019-11-20 15:47
Please provide a dataset that allows reproducing your issue.

**Comment by anntzer** [comment] 2019-12-05 13:27
Closing for lack of info, feel free to reopen with more info.

**Closed by anntzer** 2019-12-05 13:27 UTC
Labels: needs-info
