### ISSUE TITLE
Getting non-deterministic results with python 3.10

### ISSUE THREAD

**Issue by siliwangCMT** [hmmlearn/hmmlearn#490] opened 2022-11-21 15:49 UTC
## I have a question

Our in-production system uses` hmmlearn = "~=0.2.4"`; it is generating non-deterministic results with Python 3.10. Are you aware of such issues and would the latest release fix the non-deterministic part?

Thanks

**Comment by anntzer** [comment] 2022-11-21 16:56
Are you setting random_state?  If you do and still see nondeterminism, please provide an example.

**Comment by anntzer** [comment] 2022-11-28 09:10
Closing due to the lack of reproducible example, which makes this non-actionable.  Feel free to re-ping with a reproduction.

**Closed by anntzer** 2022-11-28 09:10 UTC
