### ISSUE TITLE
ImportError: cannot import name 'hmm' while it is already installed with 0.2.3 version

### ISSUE THREAD

**Issue by HYDesmondLiu** [hmmlearn/hmmlearn#374] opened 2020-02-19 17:16 UTC
Hi experts,
    I have already got hmmlearn installed on my computer however when I run "**_from hmmlearn import hmm" is outputs_** "**_ImportError: cannot import name 'hmm_**'". 
    My environment:
OS: CentOS Linux release 7.7.1908 (Core)
hmmlearn version: 0.2.3
python version: 3.6.8

**Comment by Mattyboi123** [comment] 2020-02-24 15:13
I have an equivalent issue running on python 3.7, windows 10, in spyder.
`
  File "<ipython-input-10-af4dcd8b2465>", line 10, in <module>
    from hmmlearn import hmm

  File "C:\Users\fbsmaw\anaconda3\Lib\site-packages\hmmlearn\hmm.py", line 22, in <module>
    from .base import _BaseHMM

  File "C:\Users\fbsmaw\anaconda3\Lib\site-packages\hmmlearn\base.py", line 11, in <module>
    from . import _hmm, _utils

ImportError: cannot import name '_hmm' from 'hmmlearn' (C:\Users\fbsmaw\anaconda3\Lib\site-packages\hmmlearn\__init__.py)`

any ideas anyone?

**Comment by YMandCL** [comment] 2020-02-27 19:24
Are you getting a DLL load error?
I believe this may have something to do with the following scipy dependency.

**scipy.special import logsumexp**

**Comment by anntzer** [comment] 2020-05-26 18:10
Please
1) Describe exactly how you installed hmmlearn
2) Check whether you can import scipy.special and sklearn.  If you cannot, then it means that your install of scipy/sklearn are broken in which case hmmlearn cannot do anything about it.

**Comment by rmaronson** [comment] 2020-09-09 19:36
Was about to create an issue, but I think mine is a duplicate of this.

`hmmlearn` is incompatible with `scipy`<0.19, as that version moved `logsumexp` to `scipy.special` (rather than `scipy.misc`; see https://github.com/scipy/scipy/commit/f8dda4857597b7885b395e49a852ac70fd01d52d)

`scikit-learn==0.16` only requires `scipy>=0.9`, so the `scikit-learn` dependency isn't actually enough to ensure it (see https://scikit-learn.org/0.16/install.html)

Resolution: Update documentation (and pip dependences, presumably?) to check for `scipy>=0.19`. Alternately, catch an import error on `scipy.special.logsumexp` and try `scipy.misc.logsumexp` as a backup.

**Comment by anntzer** [comment] 2020-09-09 23:43
Ah, fair enough.  Bumped the dependency bound, hopefully this will fix these problems.

**Comment by anntzer** [comment] 2020-09-12 15:19
Released v0.2.4 with the fix.

**Closed by anntzer** 2020-09-12 15:19 UTC
