### ISSUE TITLE
initial K-Means clustering in 0.2.1 has insufficient samples

### ISSUE THREAD

**Issue by lwthatcher** [hmmlearn/hmmlearn#275] opened 2018-04-05 20:06 UTC
# K-Means clustering error  (`0.2.1`)
I updated to version `0.2.1` to get around previous errors (see issue #78),
however when I've run it with some of my own data I start getting the following error:

``` python
ValueError: n_samples=2 should be >= n_clusters=3
```
Looking further it seems that just prior to this an initial k-means clustering occurs on [line 603](https://github.com/hmmlearn/hmmlearn/blob/master/hmmlearn/hmm.py#L603), using `n_components` as the number of clusters. In some circumstances the number of examples assigned to a cluster ends up being lower* than the value for `n_mix`, which results in an error during the second k-means clustering on [line 608](https://github.com/hmmlearn/hmmlearn/blob/master/hmmlearn/hmm.py#L608).

> ***Note:** so far this value for `n_clusters` has always been 2 when this error occurs

This becomes a problem when I'm still using relatively small values:
- `n_components = 6`
- `n_mix = 3`

## Error Log:
```
ValueError                                Traceback (most recent call last)
<ipython-input-5-0c105a155831> in <module>()
    110         pbar.update(1)
    111         # train x model
--> 112         zx = train_model(xi)
    113         Zx.append(zx)
    114         pbar.update(TS)

<ipython-input-5-0c105a155831> in train_model(x)
     53 def train_model(x):
     54     model = hmm.GMMHMM(N,M,covariance_type=COVAR, n_iter=ITERS)
---> 55     model.fit(x)
     56     z = model.predict(x)
     57     return z

/usr/local/lib/python3.5/dist-packages/hmmlearn-0.2.1-py3.5-linux-x86_64.egg/hmmlearn/base.py in fit(self, X, lengths)
    422         """
    423         X = check_array(X)
--> 424         self._init(X, lengths=lengths)
    425         self._check()
    426 

/usr/local/lib/python3.5/dist-packages/hmmlearn-0.2.1-py3.5-linux-x86_64.egg/hmmlearn/hmm.py in _init(self, X, lengths)
    606             kmeans = cluster.KMeans(n_clusters=self.n_mix,
    607                                     random_state=self.random_state)
--> 608             kmeans.fit(X[np.where(labels == label)])
    609             kmeanses.append(kmeans)
    610 

/usr/lib/python3/dist-packages/sklearn/cluster/k_means_.py in fit(self, X, y)
    810         """
    811         random_state = check_random_state(self.random_state)
--> 812         X = self._check_fit_data(X)
    813 
    814         self.cluster_centers_, self.labels_, self.inertia_, self.n_iter_ = \

/usr/lib/python3/dist-packages/sklearn/cluster/k_means_.py in _check_fit_data(self, X)
    787         if X.shape[0] < self.n_clusters:
    788             raise ValueError("n_samples=%d should be >= n_clusters=%d" % (
--> 789                 X.shape[0], self.n_clusters))
    790         return X
    791 

ValueError: n_samples=2 should be >= n_clusters=3
```

**Comment by ArjunWhabi** [comment] 2019-03-09 18:00
I'm having the same problem as well. 
I'm using a GmmHMM model with: 
n_components =2,  n_mix = 2

I have an array X with data of shape (50,1). 

If i try to fit(X, lengths= None) I get 
`Traceback (most recent call last):
  File "D:/WinPython-3670/backtrader/hmmindicator_strategyconstraints.py", line 291, in <module>
    cerebro.run()
  File "D:\WinPython-3670\backtrader\backtrader\cerebro.py", line 1127, in run
    runstrat = self.runstrategies(iterstrat)
  File "D:\WinPython-3670\backtrader\backtrader\cerebro.py", line 1293, in runstrategies
    self._runonce(runstrats)
  File "D:\WinPython-3670\backtrader\backtrader\cerebro.py", line 1652, in _runonce
    strat._once()
  File "D:\WinPython-3670\backtrader\backtrader\lineiterator.py", line 297, in _once
    indicator._once()
  File "D:\WinPython-3670\backtrader\backtrader\lineiterator.py", line 318, in _once
    self.once(self._minperiod, self.buflen())
  File "D:\WinPython-3670\backtrader\backtrader\indicator.py", line 136, in once_via_next
    self.next()
  File "D:/WinPython-3670/backtrader/hmmindicator_strategyconstraints.py", line 56, in next
    mdl2.fit(rets2, lengths=len)
  File "D:\WinPython-3670\backtrader\lib\site-packages\hmmlearn\base.py", line 424, in fit
    self._init(X, lengths=lengths)
  File "D:\WinPython-3670\backtrader\lib\site-packages\hmmlearn\hmm.py", line 611, in _init
    kmeans.fit(X[np.where(labels == label)])
  File "D:\WinPython-3670\backtrader\lib\site-packages\sklearn\cluster\k_means_.py", line 971, in fit
    return_n_iter=True)
  File "D:\WinPython-3670\backtrader\lib\site-packages\sklearn\cluster\k_means_.py", line 315, in k_means
    _num_samples(X), n_clusters))
ValueError: n_samples=1 should be >= n_clusters=2`

I think the issue is that we're passing 1 dimensional data into a Guassian Model which has 2 Mixtures.
It is treating the data as 1 dimensional. 
Whats the solution ?

**Comment by ArjunWhabi** [comment] 2019-03-09 18:01
I'm having the same problem as well.
I'm using a GmmHMM model with:
n_components =2, n_mix = 2

I have an array X with data of shape (50,1).

If i try to fit(X, lengths= None) I get
Traceback (most recent call last):
  File "D:/WinPython-3670/backtrader/hmmindicator_strategyconstraints.py", line 291, in <module>
    cerebro.run()
  File "D:\WinPython-3670\backtrader\backtrader\cerebro.py", line 1127, in run
    runstrat = self.runstrategies(iterstrat)
  File "D:\WinPython-3670\backtrader\backtrader\cerebro.py", line 1293, in runstrategies
    self._runonce(runstrats)
  File "D:\WinPython-3670\backtrader\backtrader\cerebro.py", line 1652, in _runonce
    strat._once()
  File "D:\WinPython-3670\backtrader\backtrader\lineiterator.py", line 297, in _once
    indicator._once()
  File "D:\WinPython-3670\backtrader\backtrader\lineiterator.py", line 318, in _once
    self.once(self._minperiod, self.buflen())
  File "D:\WinPython-3670\backtrader\backtrader\indicator.py", line 136, in once_via_next
    self.next()
  File "D:/WinPython-3670/backtrader/hmmindicator_strategyconstraints.py", line 56, in next
    mdl2.fit(rets2, lengths=len)
  File "D:\WinPython-3670\backtrader\lib\site-packages\hmmlearn\base.py", line 424, in fit
    self._init(X, lengths=lengths)
  File "D:\WinPython-3670\backtrader\lib\site-packages\hmmlearn\hmm.py", line 611, in _init
    kmeans.fit(X[np.where(labels == label)])
  File "D:\WinPython-3670\backtrader\lib\site-packages\sklearn\cluster\k_means_.py", line 971, in fit
    return_n_iter=True)
  File "D:\WinPython-3670\backtrader\lib\site-packages\sklearn\cluster\k_means_.py", line 315, in k_means
    _num_samples(X), n_clusters))
ValueError: n_samples=1 should be >= n_clusters=2

I think the issue is that we're passing 1 dimensional data into a Guassian Model which has 2 Mixtures.
It is treating the data as 1 dimensional.
Whats the solution ?

**Comment by anntzer** [comment] 2020-05-26 20:44
Please provide a reproducible example per https://github.com/hmmlearn/hmmlearn/blob/master/.github/ISSUE_TEMPLATE.md#i-am-reporting-a-bug.

**Comment by anntzer** [comment] 2021-04-23 17:44
Closing per lack of reproducible example.

**Closed by anntzer** 2021-04-23 17:44 UTC
