### ISSUE TITLE
gmms_ ?

### ISSUE THREAD

**Issue by chanansh** [hmmlearn/hmmlearn#200] opened 2017-05-14 10:56 UTC
Hi,
GMMHMM used to have a gmms_ property. Currently in the master I can find it only in the tests.
I see that the implementation path was decided to reimplement GMM rather than using sklearn's.
I believe a better decision was to use Sklearns model so that the community can benefit from the progress in one place.

**Comment by superbobry** [comment] 2017-07-19 21:50
Duplicate of #202.

**Closed by superbobry** 2017-07-19 21:50 UTC
