### ISSUE TITLE
Gaussian HMM Jupyter Notebook and code examples are not working

### ISSUE THREAD

**Issue by SteffenNa** [hmmlearn/hmmlearn#222] opened 2017-08-08 12:42 UTC
Hello. Thanks for the great Model. Wanted to work through the Gaussian HMM example but it throws an error at line 34:
```
quotes = quotes_historical_yahoo_ochl(
    "INTC", datetime.date(1995, 1, 1), datetime.date(2012, 1, 6))
```
would be great if you could fix that. Thanks

**Comment by mjjohns1** [comment] 2017-08-24 18:35
In the meantime, you can get the data here:  https://finance.yahoo.com/quote/INTC/history?p=INTC

Select 'Historical Data' and enter the date ranges into the 'Time Period' drop down menu (middle, left side). Once the data are loaded you can download them as a csv.

**Comment by SteffenNa** [comment] 2017-08-28 04:16
That you. I used pandas to download it. Maybe you want to change your example using pandas too.

**Comment by Kornel** [comment] 2017-10-04 17:45
There's also a pip package fix-yahoo-finance (sic!)

If you install this package, something like that should do the trick:

```
import fix_yahoo_finance as yf
quotes = yf.download("INTC", datetime.date(1995, 1, 1), datetime.date(2012, 1, 6))
quotes_matrix = quotes.reset_index().as_matrix()
```

However, I think we should include the data into the package, just like scikit has its' toy datasets. Otherwise such issues will be reoccurring. @superbobry  what do you think? From what I see you're the maintainer of hmmlearn?

**Comment by superbobry** [comment] 2017-10-08 22:13
I think we can copy/paste the scikit-learn parsing code for Google Finance, see scikit-learn/scikit-learn#9010.

**Comment by superbobry** [comment] 2017-10-08 22:17
Duplicate of #207.

**Closed by superbobry** 2017-10-08 22:17 UTC
