### ISSUE TITLE
GMMHMM models training not converging (?)

### ISSUE THREAD

**Issue by giorgiolbt** [hmmlearn/hmmlearn#410] opened 2021-04-23 11:19 UTC
Hi all,
I am having a problem when trying to fit multiple GMMHMM models to solve a classification problem of emotions recognition from speech samples. 
Basically, the models often don't converge: even if the monitor reports 'True' if printed, I can see in the history that the likelihood is not strictly increasing. Actually, it decreases at some point and the training procedure stops.

Here, I report only the procedure for training one of the models (I should have seven, each one trained with a different training set). The data loaded are attached: [data_training.npy.zip](https://github.com/hmmlearn/hmmlearn/files/6365097/data_training.npy.zip)

    from hmmlearn import hmm
    import numpy as np 
    data = np.load('data_training.npy', allow_pickle=True)

    hmm = hmm.GMMHMM(n_components=2, n_mix=2,n_iter=1000, covariance_type="diag", verbose=True ) 

    X_sequence_concat = np.concatenate(data) 
    lengths = []
    for el in data:
        lengths.append(len(el))

    hmm.fit(X_sequence_concat, np.array(lengths))   
    print("Is the HMM training converged? " + str(hmm.monitor_.converged))

In my actual implementation I have to do this for seven different models and sometimes I get this problem and sometimes I don't, as you can see from the results reported below:

<img width="424" alt="Schermata 2021-04-23 alle 13 14 43" src="https://user-images.githubusercontent.com/37977090/115863608-0096bc80-a436-11eb-8f96-89603d4c82b3.png">

Can you please help me? I'm really struggling with this and I can't find a possible cause of the problem.

Thanks in advance!

**Comment by anntzer** [comment] 2021-04-23 11:28
Per the issue template:

- Provide a short, self-contained, correct example (http://sscce.org/).
  Maintainers must be able to reproduce the issue **by copy-pasting your
  example in a new, empty file/console/notebook**.  Avoid including data files
  as much as possible; if they are absolutely necessary, they must be in csv or
  npy format, and code for loading the file must be included in the example.

Issues not reproducible with the latest release of hmmlearn or without a short,
self-contained, correct example **will be closed**.

**Comment by giorgiolbt** [comment] 2021-04-23 13:26
Thanks, I updated the issue in order to respect the template.

**Comment by anntzer** [comment] 2021-04-23 17:43
Thanks.  I can reproduce the failure.
Possibly this may be just due to floating point inaccuracies (the relative decrease is not very large), but it's hard for me to say.  To be honest the GMMHMM part of the code seems a bit iffy (see #78, #107, 655186e) and I'm not claiming any familiarity with it.

**Comment by giorgiolbt** [comment] 2021-04-23 19:22
Hi Antony!
I'm not sure I got what you meant. I tried changing the precision of the float numbers, but I still have the same problem. I also didn't get what you were saying about the code being iffy. I'm really sorry, can you provide further explanations?

**Comment by anntzer** [comment] 2021-04-23 20:17
By precision I mean that the formulas implemented may accumulate some floating point error (https://en.wikipedia.org/wiki/Floating-point_error_mitigation).  As for the iffyness, well, I don't really know as again I'm not familiar with that part of the codebase, but I'm not too confident about it either :)

**Comment by giorgiolbt** [comment] 2021-04-26 09:20
Unfortunately, I tried to extend precision to a maximum, but even in this case, I have the same problem. Do you have any other suggestions? It really seems to be a problem with the data. I don't know if it can depends on their amount: I have 71 samples in each of the seven training sets, I tried extending them (just duplicating them), but it didn't work either. The data have 18 features while the length (number of rows) of each sample is not constant

**Comment by anntzer** [comment] 2021-04-26 09:34
I unfortunately don't have any suggestion.  I genuinely believe this *may* be a bug (or rather an inaccuracy) in the implementation, but don't know enough to investigate or fix it.

**Comment by giorgiolbt** [comment] 2021-04-26 10:25
Ok thanks Antony, do you think that someone will have a look into it?

**Comment by anntzer** [comment] 2021-04-26 10:36
No one is in charge of that part of the codebase.

**Comment by fcostin** [comment] 2021-07-03 10:26
This issue and the issues hinted at in https://github.com/hmmlearn/hmmlearn/issues/377 seem very similar.

Common symptoms:

* GMMHMM convergence problems occur during a GMMHMM fit on data (X, lengths) containing multiple sequences (aka multiple frames)
* During a `fit`, we expect EM iterations to maximise the log likelihood to some local maxima, depending on initial conditions. The log likelihood should be non-decreasing (ignoring numerical error) between successive EM iterations. But we see in this this issue report and as reported anecdotally in issue 337 we see the convergence monitor showing iterations with large _decreases_ in log likelihood -- this is not meant to happen

I am not familiar with HMM or the hmmlearn code so I may be getting confused, but from reading through the code and comparing GMMHMM implementation of `_accumulate_sufficient_statistics` to the other `_accumulate_sufficient_statistics` implementations, it looks like GMMHMM `_accumulate_sufficient_statistics` implementation -- as used during EM iterations during fitting -- doesn't support multiple sequences:

https://github.com/hmmlearn/hmmlearn/blob/85ec0bcf279ea357f737bdbdd3338402650706d3/lib/hmmlearn/hmm.py#L903-L931

Note the comment: "# TODO: support multiple frames" -- aka "support multiple sequences". The GMMHMM code simply does not implement support for fitting to data with more than one sequence aka frame.

FirstHandScientist suggested this same problem with the GMMHMM code as an explanation for log likelihood decrease in 2019 when discussing a different issue report. https://github.com/hmmlearn/hmmlearn/issues/348#issuecomment-515487162

I believe the problem is that  `_accumulate_sufficient_statistics` does not _accumulate_ anything -- it _overwrites_ the previous result. This means that during each EM iteration when the base class iteratively calls `_accumulate_sufficient_statistics` once per sequence, the sufficient statistics computations from all of the sequences except the last sequence are thrown away without being used and only data from the last sequence is considered during M-step inside GMMHMM `_do_mstep`. This means that GMMHMM will be executing a strange variation of EM where it ignores data from many (most?) samples during maximisation of the GMM parameters, but not during other parts of the algorithm -- this could explain why we see the log likelihood actually getting worse between successive iterations.

It looks like this limitation was introduced in october 2016 as part of a big GMMHMM rewrite: https://github.com/hmmlearn/hmmlearn/pull/107

The limitation was noticed during code review but the decision was made to merge the PR before it was fixed, and then it wasn't fixed (or documented):

> Ensure that the implemented M-step correctly handles multiple sequences. _BaseHMM simply sums up the sufficient statistics over all of the sequences.

### what now?

* a low-effort change to mitigate the issue could be to update GMMHMM documentation and/or update GMMHMM fit method to raise a warning or raise a `NotImplementedError` whenever it is run with more than one sequence, to tell the user that the code doesn't work in that scenario
*

**Comment by fcostin** [comment] 2021-07-03 10:46
Here's a very rough patch for GMMHMM multi sequence support, trying to make shapes of various arrays conform and do something semi-plausible but perhaps wrong to splice together different chunks of data belonging to different sequences along the samples axis. Maths may be wrong.

From testing it manually with the data on this issue, after applying the patch the divergence problem disappears. The EM iterations converge, but the reported log likelihood is a bit less than what we see in the original issue report before the iterations diverge:

...
        33    14187696.6553          +0.0215
        34    14187696.6704          +0.0151
        35    14187696.6809          +0.0106
        36    14187696.6883          +0.0074
```

```
From 0eb5c04ad1fd20d01d89ab30022179ae385ab81f Mon Sep 17 00:00:00 2001
From: rfc
Date: Sat, 3 Jul 2021 18:21:17 +1000
Subject: [PATCH 1/3] experimental fix for gmmhmm multi sequence accumulate

---
 lib/hmmlearn/hmm.py | 70 ++++++++++++++++++++++++++++++++-------------
 1 file changed, 50 insertions(+), 20 deletions(-)

diff --git a/lib/hmmlearn/hmm.py b/lib/hmmlearn/hmm.py
index e49a0d0..6cc9084 100644
--- a/lib/hmmlearn/hmm.py
+++ b/lib/hmmlearn/hmm.py
@@ -893,26 +893,42 @@ class GMMHMM(_BaseHMM):
     def _initialize_sufficient_statistics(self):
         stats = super()._initialize_sufficient_statistics()
         stats['n_samples'] = 0
-        stats['post_comp_mix'] = None
         stats['post_mix_sum'] = np.zeros((self.n_components, self.n_mix))
         stats['post_sum'] = np.zeros(self.n_components)
-        stats['samples'] = None
-        stats['centered'] = None
+
+        # FIXME the following all require memory proportional to the
+        # number of samples. It would be preferable to rework the
+        # calculations in _do_mstep to reduce over the samples axis
+        # earlier during _accumulate_sufficient_statistics in order
+        # to make memory consumption independent of the number of
+        # samples.
+
+        # HACK-ish:
+        # The following are lists so we can accumulate chunks of
+        # data for multiple sequences (aka multiple frames) during
+        # fitting. The fit(X, lengths) method in the base class
+        # will call _accumulate_sufficient_statistics
+        # once per sequence in the training samples. Data from all
+        # sequences needs to be accumulated and fed into _do_mstep .
+        # Each list will accumulate one item per sequence.
+        # The sum over items of the first dimension should equal the
+        # total number of samples.
+        stats['post_comp_mix'] = [] # when vstack'd will have shape (n_samples, n_components, n_mix)
+        stats['samples'] = [] # when vstack'd will have shape (n_samples, n_features)
+        stats['centered'] = [] # when vstack'd will have shape (n_samples, n_components, n_mix, n_features)
         return stats
 
     def _accumulate_sufficient_statistics(self, stats, X, framelogprob,
                                           post_comp, fwdlattice, bwdlattice):
 
-        # TODO: support multiple frames
-
         super()._accumulate_sufficient_statistics(
             stats, X, framelogprob, post_comp, fwdlattice, bwdlattice
         )
 
         n_samples, _ = X.shape
 
-        stats['n_samples'] = n_samples
-        stats['samples'] = X
+        stats['n_samples'] += n_samples
+        stats['samples'].append(X)
 
         post_mix = np.zeros((n_samples, self.n_components, self.n_mix))
         for p in range(self.n_components):
@@ -923,19 +939,33 @@ class GMMHMM(_BaseHMM):
 
         with np.errstate(under="ignore"):
             post_comp_mix = post_comp[:, :, None] * post_mix
-        stats['post_comp_mix'] = post_comp_mix
+        stats['post_comp_mix'].append(post_comp_mix)
 
-        stats['post_mix_sum'] = post_comp_mix.sum(axis=0)
-        stats['post_sum'] = post_comp.sum(axis=0)
+        stats['post_mix_sum'] += post_comp_mix.sum(axis=0)
+        stats['post_sum'] += post_comp.sum(axis=0)
 
-        stats['centered'] = X[:, None, None, :] - self.means_
+        stats['centered'].append(X[:, None, None, :] - self.means_)
 
     def _do_mstep(self, stats):
         super()._do_mstep(stats)
+        ns = stats['n_samples']
         nc = self.n_components
         nf = self.n_features
         nm = self.n_mix
 
+
+        # aggregate post_comp_mix data from multiple sequences
+        post_comp_mix = np.vstack(stats['post_comp_mix'])
+        assert post_comp_mix.shape == (ns, nc, nm)
+
+        # aggregate samples data from multiple sequences
+        samples = np.vstack(stats['samples'])
+        assert samples.shape == (ns, nf)
+
+        # aggregate centered data from multiple sequences
+        centered = np.vstack(stats['centered'])
+        assert centered.shape == (ns, nc, nm, nf)
+
         # Maximizing weights
         if 'w' in self.params:
             alphas_minus_one = self.weights_prior - 1
@@ -948,7 +978,7 @@ class GMMHMM(_BaseHMM):
             lambdas, mus = self.means_weight, self.means_prior
             m_n = (
                 np.einsum('ijk,il->jkl',
-                          stats['post_comp_mix'], stats['samples'])
+                          post_comp_mix, samples)
                 + lambdas[:, :, None] * mus
             )
             m_d = stats['post_mix_sum'] + lambdas
@@ -968,7 +998,7 @@ class GMMHMM(_BaseHMM):
                 return x[..., :, None] * x[..., None, :]
 
             if self.covariance_type == 'full':
-                centered_dots = outer_f(stats['centered'])
+                centered_dots = outer_f(centered)
                 centered_means_dots = outer_f(centered_means)
 
                 psis_t = np.transpose(self.covars_prior, axes=(0, 1, 3, 2))
@@ -976,7 +1006,7 @@ class GMMHMM(_BaseHMM):
 
                 c_n = (
                     np.einsum('ijk,ijklm->jklm',
-                              stats['post_comp_mix'], centered_dots)
+                              post_comp_mix, centered_dots)
                     + psis_t
                     + lambdas[:, :, None, None] * centered_means_dots
                 )
@@ -985,7 +1015,7 @@ class GMMHMM(_BaseHMM):
                 )[:, :, None, None]
 
             elif self.covariance_type == 'diag':
-                centered2 = stats['centered'] ** 2
+                centered2 = centered ** 2
                 centered_means2 = centered_means ** 2
 
                 alphas = self.covars_prior
@@ -993,14 +1023,14 @@ class GMMHMM(_BaseHMM):
 
                 c_n = (
                     np.einsum('ijk,ijkl->jkl',
-                              stats['post_comp_mix'], centered2)
+                              post_comp_mix, centered2)
                     + lambdas[:, :, None] * centered_means2
                     + 2 * betas
                 )
                 c_d = stats['post_mix_sum'][:, :, None] + 1 + 2 * (alphas + 1)
 
             elif self.covariance_type == 'spherical':
-                centered_norm2 = (stats['centered'] ** 2).sum(axis=-1)
+                centered_norm2 = (centered ** 2).sum(axis=-1)
                 centered_means_norm2 = (centered_means ** 2).sum(axis=-1)
 
                 alphas = self.covars_prior
@@ -1008,14 +1038,14 @@ class GMMHMM(_BaseHMM):
 
                 c_n = (
                     np.einsum(
-                        'ijk,ijk->jk', stats['post_comp_mix'], centered_norm2)
+                        'ijk,ijk->jk', post_comp_mix, centered_norm2)
                     + lambdas * centered_means_norm2
                     + 2 * betas
                 )
                 c_d = nf * (stats['post_mix_sum'] + 1) + 2 * (alphas + 1)
 
             elif self.covariance_type == 'tied':
-                centered_dots = outer_f(stats['centered'])
+                centered_dots = outer_f(centered)
                 centered_means_dots = outer_f(centered_means)
 
                 psis_t = np.transpose(self.covars_prior, axes=(0, 2, 1))
@@ -1023,7 +1053,7 @@ class GMMHMM(_BaseHMM):
 
                 c_n = (
                     np.einsum('ijk,ijklm->jlm',
-                              stats['post_comp_mix'], centered_dots)
+                              post_comp_mix, centered_dots)
                     + np.einsum('ij,ijkl->ikl', lambdas, centered_means_dots)
                     + psis_t
                 )
-- 
2.25.1
```

**Comment by anntzer** [comment] 2021-07-03 12:21
I agree with all of your points, and from a *very* quick look, the patch seems reasonable as well.

**Comment by fcostin** [comment] 2021-07-03 12:25
> I agree with all of your points, and from a very quick look, the patch seems reasonable as well.

thank you for doing a quick review.  i have no expectation of anyone fixing this, if i've still got a bit of momentum tomorrow i'll aim to put together a PR with a corresponding test or two.

my patch as-is would have impact of adding some unnecessary copying (with the vstacks) especially in the case of 1 sequence that already works.  may be able to tweak it to use less memory.

**Comment by anntzer** [comment] 2021-07-03 12:28
I wouldn't worry too much about the memory consumption for now, I think that's just a constant factor anyways (perhaps 2x more basically), which seems like an OK cost given that the thing was just completely wrong before...

**Comment by fcostin** [comment] 2021-07-04 01:02
i've raised a rough PR that proposes a new test based on data from this issue that is able to detect brokenness and passes when the above patch is applied:

https://github.com/hmmlearn/hmmlearn/pull/417

i haven't reviewed the patches myself yet for readability & style, will do another self-review pass tomorrow

@anntzer , any review feedback (or CI feedback) appreciated if you have bandwidth

**Comment by anntzer** [comment] 2021-07-18 14:04
@fcostin has kindly provided a fix to fit multiple sequences using GMMHMM, which was previously not supported.  This is now released as hmmlearn 0.2.6.  Please consider upgrading to it, and reopen the issue if your problem is still present.

**Closed by anntzer** 2021-07-18 14:04 UTC
Labels: bug
