### ISSUE TITLE
Import error: name 'logsumexp'

### ISSUE THREAD

**Issue by ChenChenGith** [hmmlearn/hmmlearn#320] opened 2018-12-05 12:42 UTC
I use the latest committed version (not the released version). When importing hmm, there is a question:

`from hmmlearn import hmm`
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-8b8c029fb053> in <module>()
----> 1 from hmmlearn import hmm

C:\Anaconda3\lib\site-packages\hmmlearn\__init__.py in <module>()
      3 from sklearn.utils import check_random_state
      4 
----> 5 from hmmlearn.utils import normalize
      6 
      7 # Make NumPy complain about underflows/overflows etc.

C:\Anaconda3\lib\site-packages\hmmlearn\utils.py in <module>()
      1 import numpy as np
----> 2 from scipy.special import logsumexp
      3 
      4 
      5 def normalize(a, axis=None):

ImportError: cannot import name 'logsumexp'

A similar question   #63 in 2015. But it is differet. The code has changes a lot.

This may some reference error when import SciPy. How could I do to correctely import hmm?

my SciPy version is 1.1.0

**Comment by ChenChenGith** [comment] 2018-12-05 13:03
I am the questioner.
I check the files in SciPy. I is found that the name 'logsumexp' has been changed to '_logsumexp'
Modifying the code 
`from scipy.special import logsumexp` 
in hmm.py to 
`from scipy.special import logsumexp`
can solve this question.
However, there is a new error:
```
ImportError                               Traceback (most recent call last)
<ipython-input-15-bfa3649d8747> in <module>()
      1 import numpy as np
----> 2 from hmmlearn import hmm

C:\Anaconda3\lib\site-packages\hmmlearn\hmm.py in <module>()
     13 import numpy as np
     14 from scipy.special import _logsumexp as logsumexp
---> 15 from sklearn import cluster
     16 from sklearn.utils import check_random_state
     17 

C:\Anaconda3\lib\site-packages\sklearn\cluster\__init__.py in <module>()
      4 """
      5 
----> 6 from .spectral import spectral_clustering, SpectralClustering
      7 from .mean_shift_ import (mean_shift, MeanShift,
      8                           estimate_bandwidth, get_bin_seeds)

C:\Anaconda3\lib\site-packages\sklearn\cluster\spectral.py in <module>()
     13 from ..utils import check_random_state, as_float_array
     14 from ..utils.validation import check_array
---> 15 from ..metrics.pairwise import pairwise_kernels
     16 from ..neighbors import kneighbors_graph
     17 from ..manifold import spectral_embedding

C:\Anaconda3\lib\site-packages\sklearn\metrics\__init__.py in <module>()
     32 from .classification import brier_score_loss
     33 
---> 34 from . import cluster
     35 from .cluster import adjusted_mutual_info_score
     36 from .cluster import adjusted_rand_score

C:\Anaconda3\lib\site-packages\sklearn\metrics\cluster\__init__.py in <module>()
     18 from .supervised import fowlkes_mallows_score
     19 from .supervised import entropy
---> 20 from .unsupervised import silhouette_samples
     21 from .unsupervised import silhouette_score
     22 from .unsupervised import calinski_harabaz_score

C:\Anaconda3\lib\site-packages\sklearn\metrics\cluster\unsupervised.py in <module>()
     15 from ...utils import check_X_y
     16 from ...utils import safe_indexing
---> 17 from ..pairwise import pairwise_distances_chunked
     18 from ..pairwise import pairwise_distances
     19 from ...preprocessing import LabelEncoder

C:\Anaconda3\lib\site-packages\sklearn\metrics\pairwise.py in <module>()
     15 
     16 import numpy as np
---> 17 from scipy.spatial import distance
     18 from scipy.sparse import csr_matrix
     19 from scipy.sparse import issparse

C:\Anaconda3\lib\site-packages\scipy\spatial\__init__.py in <module>()
     94 from .kdtree import *
     95 from .ckdtree import *
---> 96 from .qhull import *
     97 from ._spherical_voronoi import SphericalVoronoi
     98 from ._plotutils import *

ImportError: DLL load failed: The specified module could not be found.
```
I think there must some question in sklearn beacause the error is proposed by 
`from sklearn import cluster `

Now I really don't know what to do.

My sklearn version is : 0.20.1  the newest version.

**Comment by anntzer** [comment] 2018-12-05 13:30
If you cannot import sklearn.cluster then please report the bug on their tracker -- there isn't anything hmmlearn can do.

**Comment by anntzer** [comment] 2018-12-07 20:38
Closing as the issue is on sklearn's side, feel free to reping once you got that solved.

**Closed by anntzer** 2018-12-07 20:38 UTC
