### ISSUE TITLE
Get error when run tests

### ISSUE THREAD

**Issue by ndhir** [hmmlearn/hmmlearn#36] opened 2015-06-17 16:30 UTC
I get the following error when I try to run the tests under sect **Running the test suite**:

```
./hmmlearn$ sudo python setup.py build_ext --inplace && nosetests
running build_ext
copying build/lib.linux-x86_64-2.7/hmmlearn/_hmmc.so -> hmmlearn
EEE..
======================================================================
ERROR: Failure: ImportError (cannot import name check_arrays)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/local/neild/cloud/LIBRARIES/hmmlearn/hmmlearn/hmm.py", line 16, in <module>
    from sklearn.mixture import (
  File "/usr/local/lib/python2.7/dist-packages/sklearn/mixture/__init__.py", line 5, in <module>
    from .gmm import sample_gaussian, log_multivariate_normal_density
  File "/usr/local/lib/python2.7/dist-packages/sklearn/mixture/gmm.py", line 20, in <module>
    from .. import cluster
  File "/usr/local/lib/python2.7/dist-packages/sklearn/cluster/__init__.py", line 6, in <module>
    from .spectral import spectral_clustering, SpectralClustering
  File "/usr/local/lib/python2.7/dist-packages/sklearn/cluster/spectral.py", line 16, in <module>
    from ..metrics.pairwise import pairwise_kernels
  File "/usr/local/lib/python2.7/dist-packages/sklearn/metrics/__init__.py", line 31, in <module>
    from . import cluster
  File "/usr/local/lib/python2.7/dist-packages/sklearn/metrics/cluster/__init__.py", line 21, in <module>
    from .bicluster import consensus_score
  File "/usr/local/lib/python2.7/dist-packages/sklearn/metrics/cluster/bicluster/__init__.py", line 1, in <module>
    from .bicluster_metrics import consensus_score
  File "/usr/local/lib/python2.7/dist-packages/sklearn/metrics/cluster/bicluster/bicluster_metrics.py", line 6, in <module>
    from sklearn.utils.validation import check_arrays
ImportError: cannot import name check_arrays

======================================================================
ERROR: Failure: ImportError (cannot import name check_arrays)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/local/neild/cloud/LIBRARIES/hmmlearn/hmmlearn/tests/test_base.py", line 9, in <module>
    from hmmlearn import hmm
  File "/local/neild/cloud/LIBRARIES/hmmlearn/hmmlearn/hmm.py", line 16, in <module>
    from sklearn.mixture import (
  File "/usr/local/lib/python2.7/dist-packages/sklearn/mixture/__init__.py", line 5, in <module>
    from .gmm import sample_gaussian, log_multivariate_normal_density
  File "/usr/local/lib/python2.7/dist-packages/sklearn/mixture/gmm.py", line 20, in <module>
    from .. import cluster
  File "/usr/local/lib/python2.7/dist-packages/sklearn/cluster/__init__.py", line 6, in <module>
    from .spectral import spectral_clustering, SpectralClustering
  File "/usr/local/lib/python2.7/dist-packages/sklearn/cluster/spectral.py", line 16, in <module>
    from ..metrics.pairwise import pairwise_kernels
  File "/usr/local/lib/python2.7/dist-packages/sklearn/metrics/__init__.py", line 31, in <module>
    from . import cluster
  File "/usr/local/lib/python2.7/dist-packages/sklearn/metrics/cluster/__init__.py", line 21, in <module>
    from .bicluster import consensus_score
  File "/usr/local/lib/python2.7/dist-packages/sklearn/metrics/cluster/bicluster/__init__.py", line 1, in <module>
    from .bicluster_metrics import consensus_score
  File "/usr/local/lib/python2.7/dist-packages/sklearn/metrics/cluster/bicluster/bicluster_metrics.py", line 6, in <module>
    from sklearn.utils.validation import check_arrays
ImportError: cannot import name check_arrays

======================================================================
ERROR: Failure: ImportError (cannot import name check_arrays)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/local/neild/cloud/LIBRARIES/hmmlearn/hmmlearn/tests/test_hmm.py", line 9, in <module>
    from sklearn import mixture
  File "/usr/local/lib/python2.7/dist-packages/sklearn/mixture/__init__.py", line 5, in <module>
    from .gmm import sample_gaussian, log_multivariate_normal_density
  File "/usr/local/lib/python2.7/dist-packages/sklearn/mixture/gmm.py", line 20, in <module>
    from .. import cluster
  File "/usr/local/lib/python2.7/dist-packages/sklearn/cluster/__init__.py", line 6, in <module>
    from .spectral import spectral_clustering, SpectralClustering
  File "/usr/local/lib/python2.7/dist-packages/sklearn/cluster/spectral.py", line 16, in <module>
    from ..metrics.pairwise import pairwise_kernels
  File "/usr/local/lib/python2.7/dist-packages/sklearn/metrics/__init__.py", line 31, in <module>
    from . import cluster
  File "/usr/local/lib/python2.7/dist-packages/sklearn/metrics/cluster/__init__.py", line 21, in <module>
    from .bicluster import consensus_score
  File "/usr/local/lib/python2.7/dist-packages/sklearn/metrics/cluster/bicluster/__init__.py", line 1, in <module>
    from .bicluster_metrics import consensus_score
  File "/usr/local/lib/python2.7/dist-packages/sklearn/metrics/cluster/bicluster/bicluster_metrics.py", line 6, in <module>
    from sklearn.utils.validation import check_arrays
ImportError: cannot import name check_arrays

----------------------------------------------------------------------
Ran 5 tests in 0.148s

FAILED (errors=3)
```

**Comment by superbobry** [comment] 2015-06-17 18:23
Which version of `scikit-learn` are you using?

**Comment by ndhir** [comment] 2015-06-17 18:49
I reinstalled ``numpy, scipy and scikit-learn`` that solved that problem, but introduced a whole load of others. The module is now basically not recognised at all. So I gave up and just imported an old version of ``sklearn`` and took ``hmmlearn`` from there.

**Comment by superbobry** [comment] 2015-06-17 19:05
I see, `check_arrays` was removed in 0.16. I'll update the `master` version soon.

> The module is now basically not recognised at all.
Do you mean there's another `ImportError`?

**Comment by superbobry** [comment] 2015-08-15 10:42
Closing, since the issue is not related to `hmmlearn`.

**Closed by superbobry** 2015-08-15 10:42 UTC
