### ISSUE TITLE
YAHOO finance API has been broken

### ISSUE THREAD

**Issue by mo10** [hmmlearn/hmmlearn#267] opened 2018-01-18 06:49 UTC
Hi,
I tried to use `examples/plot_hmm_stock_analysis.py`, but I got a problem.
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./plot_hmm_stock_analysis.py", line 33, in <module>
    "INTC", datetime.date(1995, 1, 1), datetime.date(2012, 1, 6))
  File "/usr/lib/python3.6/site-packages/matplotlib/finance.py", line 411, in quotes_historical_yahoo_ochl
    ochl=True)
  File "/usr/lib/python3.6/site-packages/matplotlib/finance.py", line 501, in _quotes_historical_yahoo
    fh = fetch_historical_yahoo(ticker, date1, date2, cachename)
  File "/usr/lib/python3.6/site-packages/matplotlib/finance.py", line 360, in fetch_historical_yahoo
    with contextlib.closing(urlopen(url)) as urlfh:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
```
YAHOO finance API services seem to have been closed.This problem may need to be repaired.

Thank you!

**Comment by anntzer** [comment] 2018-09-28 13:19
Duplicate of #207.

**Closed by anntzer** 2018-09-28 13:19 UTC
