### ISSUE TITLE
left-right HMM?

### ISSUE THREAD

**Issue by shiyuangu** [hmmlearn/hmmlearn#47] opened 2015-09-04 22:16 UTC
It seems that hmmlearn assumes fully connected (ergodic) HMM when fitting the data. Is there a way to specify other types of HMM? eg. left-right HMM?.

**Comment by soupault** [comment] 2015-10-06 13:29
Duplicate of https://github.com/hmmlearn/hmmlearn/issues/33

**Comment by superbobry** [comment] 2015-10-14 15:51
This is possible as of 03dd25107b940542b72513ca45ef57da22aac298, see commit message and [`test_fit_left_right`](https://github.com/hmmlearn/hmmlearn/blob/03dd25107b940542b72513ca45ef57da22aac298/hmmlearn/tests/test_hmm.py#L214) for details.

**Closed by superbobry** 2015-10-14 15:51 UTC
