### ISSUE TITLE
Memory error : HMM for MFCC feautres

### ISSUE THREAD

**Issue by epratheeban** [hmmlearn/hmmlearn#131] opened 2016-06-27 08:57 UTC
I am trying to create audio vocabulary from MFCC features by applying HMM. Since I have 10 speakers in the MFCC features. I need 50 states per speaker. So I used N = 500 states and it throws Memory error, but  it works fine with N =100 states.

`Memory Error` is because of computational in efficiency of a machine or due to in proper initialization?

Here is my code

```
import numpy as np
from hmmlearn import hmm
import librosa
import matplotlib.pyplot as plt

def getMFCC(episode):

    filename = getPathToGroundtruth(episode)

    y, sr = librosa.load(filename)  # Y gives 

    data = librosa.feature.mfcc(y=y, sr=sr)

    return data

def hmm_init(n,data):  #n = states d = no of feautures

    states =[]

    model = hmm.GaussianHMM(n_components=N, covariance_type="full")

    model.transmat_ = np.ones((N, N)) / N

    model.startprob_ = np.ones(N) / N

    fit = model.fit(data.T)

    z=fit.decode(data.T,algorithm='viterbi')[1]

    states.append(z)

    return states

data_m = getMFCC(1)  # Provides MFCC features of numpy array [20 X 56829]

N = 500

D= len(data)

states = hmm_init(N,data)

In [23]: run Final_hmm.py
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
/home/elancheliyan/Final_hmm.py in <module>()
     73 D= len(data)
     74 
---> 75 states = hmm_init(N,data)
     76 states.dump("states")
     77 

/home/elancheliyan/Final_hmm.py in hmm_init(n, data)
     57     model.startprob_ = np.ones(N) / N
     58 
---> 59     fit = model.fit(data.T)
     60 
     61     z=fit.decode(data.T,algorithm='viterbi')[1]

/cal/homes/elancheliyan/.local/lib/python3.5/site-packages/hmmlearn-0.2.1-py3.5-linux-x86_64.egg/hmmlearn/base.py in fit(self, X, lengths)
    434                 self._accumulate_sufficient_statistics(
    435                     stats, X[i:j], framelogprob, posteriors, fwdlattice,
--> 436                     bwdlattice)
    437 
    438             # XXX must be before convergence check, because otherwise

/cal/homes/elancheliyan/.local/lib/python3.5/site-packages/hmmlearn-0.2.1-py3.5-linux-x86_64.egg/hmmlearn/hmm.py in _accumulate_sufficient_statistics(self, stats, obs, framelogprob, posteriors, fwdlattice, bwdlattice)
    221                                           posteriors, fwdlattice, bwdlattice):
    222         super(GaussianHMM, self)._accumulate_sufficient_statistics(
--> 223             stats, obs, framelogprob, posteriors, fwdlattice, bwdlattice)
    224 
    225         if 'm' in self.params or 'c' in self.params:

/cal/homes/elancheliyan/.local/lib/python3.5/site-packages/hmmlearn-0.2.1-py3.5-linux-x86_64.egg/hmmlearn/base.py in _accumulate_sufficient_statistics(self, stats, X, framelogprob, posteriors, fwdlattice, bwdlattice)
    620                 return
    621 
--> 622             lneta = np.zeros((n_samples - 1, n_components, n_components))
    623             _hmmc._compute_lneta(n_samples, n_components, fwdlattice,
    624                                  log_mask_zero(self.transmat_),

MemoryError:

```

**Comment by superbobry** [comment] 2016-06-27 09:39
`MemoryError` means that NumPy failed to allocate an array of required shape because there was not enough memory available. 

The size of `lneta` is quadratic in the number of components, therefore for 500 components and **a single observation** you would need 500**2 * 8 ≈ 2Mb of memory.

**Comment by epratheeban** [comment] 2016-06-27 13:58
Ok, Which means I have 56,829 observations , Do I require a 2Mb * 56829 = 112 GB memory  approximately ? That don't make sense .

Can you please tell me how to solve this ?  My machine has 4 core processor with 8 GB ram and 700 GB ROM

**Comment by superbobry** [comment] 2016-06-27 16:45
Sorry, I should've explained where the above number comes from. 

As part of HMM parameter estimation you need to compute the probability of transitioning from component `i` to component `j` at observation `t`. Therefore, you need a matrix of shape `n_components * n_components * n_observations`. In your particular case the total number of items in a matrix is 

```
>>> 500 * 500 * 56829
14207250000
```

Each element is stored as [double](https://en.wikipedia.org/wiki/Double-precision_floating-point_format) which takes 8 bytes. This give us a total of

```
>>> 500 * 500 * 56829 * 8 / (2**20)  # in Mb
108392.71545410156
```

I'm not sure how to solve this without significantly changing the learning algorithm. Anyway, I'll do a search in the literature and post the results here.

**Comment by epratheeban** [comment] 2016-06-28 02:09
Thank you for the clear explanation. Now I got it clear. 

Yes, please post if you any suggestions .

**Comment by epratheeban** [comment] 2016-07-03 12:21
@superbobry  You asked me to split the data and  avoid the memory error. Here are my doubts.
1. I believe by splitting MFCC data and training it will not provide same results (may be similar results.) since I modelled the Hmm by Baum–Welch algorithm, for every splitted data it creates new initialisation and the probable states after decoding will not be same for each splitted data
2.  Secondly, Is it possible to cascade the training results to next data ?
Is my understanding is  correct ?

**Comment by superbobry** [comment] 2016-07-09 18:00
> This will create discrepancy ? Am I right here ? 

You're right splitting a sequence into multiple sequences might lead to different estimates.

> Secondly, Is it possible to cascade the training results to next data ? Is it possible to do like that ?

Yes, you can just call `fit` again on an already trained HMM, but don't forget to set `init_params` to `""`, otherwise the parameter would be re-initialized from the new data.

Getting back to the original issue, I came around a [paper](http://www.machinelearning.org/proceedings/icml2005/papers/101_FastInference_SiddiqiMoore.pdf) which gives an algorithm for learning HMMs with large state space. In a nutshell, the idea is to only estimate the transition probabilities which are "large enough". This gives a reduction in both estimation time and memory consumption. I will see if we could incorporate a similar heuristic into the current implementation.

The good news is that even if we don't get to implement the algorithm from the paper, we could still reduce memory consumption a bit. TBC in a commit message ;)

**Comment by superbobry** [comment] 2016-07-09 22:04
@epratheeban could you try fitting your data with the `master` version?

**Comment by epratheeban** [comment] 2016-07-10 09:31
@superbobry  Thank you ! Will you please tell me how to update this version in my machine ? Sorry for such lame question.

**Comment by superbobry** [comment] 2016-07-10 09:56
If you've cloned the repo do this in the repo root

```
$ git checkout d9eabf4
$ pip install .
```

or, you just install the archive directly

```
$ pip install https://github.com/hmmlearn/hmmlearn/archive/d9eabf4a6b493c8867a8b14c7fbb6ac8db84fe2b.zip
```

**Comment by epratheeban** [comment] 2016-07-10 10:58
I tried to split the data and train. 

1. Now I'm splitting 56829 observation into  57 pieces (zero padded last 171 observation) ,where each piece has 1000 observation by doing this 

```
In [3]: 500*500*1000*8/(2**20)
Out[3]: 1907.3486328125
```
This will take 2 Gb memory approximately . 

Below I splitted the total observation into 57 pieces .
```
In [27]: data = np.load("data.dat")

In [28]: ap = np.zeros((20,171))

In [29]: data.shape
Out[29]: (20, 56829)

In [30]: ap.shape
Out[30]: (20, 171)

In [31]: datar=np.c_[data,ap]

In [32]: datar.shape
Out[32]: (20, 57000)

In [33]: data_split = np.hsplit(datar,57)

In [34]: data_split[0].shape
Out[34]: (20, 1000)
```
and then I added `init_params = " "`. I know  here I am doing to something logically wrong will you please correct me 
```
states = []
for i in data_split:
    model = hmm.GaussianHMM(n_components=n, covariance_type="full",init_params="")
    model.transmat_ = np.ones((n, n)) / n
    model.startprob_ = np.ones(n) / n
    fit = model.fit(i.T)
    z=fit.decode(i.T,algorithm = 'viterbi')[1]
    states.append(z)
```
by doing this I got this error.

```
---------------------------------------------------------------------------
LinAlgError                               Traceback (most recent call last)
/Users/elancheliyan/anaconda/lib/python3.5/site-packages/sklearn/mixture/gmm.py in _log_multivariate_normal_density_full(X, means, covars, min_covar)
    700         try:
--> 701             cv_chol = linalg.cholesky(cv, lower=True)
    702         except linalg.LinAlgError:

/Users/elancheliyan/anaconda/lib/python3.5/site-packages/scipy/linalg/decomp_cholesky.py in cholesky(a, lower, overwrite_a, check_finite)
     80     c, lower = _cholesky(a, lower=lower, overwrite_a=overwrite_a, clean=True,
---> 81                             check_finite=check_finite)
     82     return c

/Users/elancheliyan/anaconda/lib/python3.5/site-packages/scipy/linalg/decomp_cholesky.py in _cholesky(a, lower, overwrite_a, clean, check_finite)
     29     if info > 0:
---> 30         raise LinAlgError("%d-th leading minor not positive definite" % info)
     31     if info < 0:

LinAlgError: 3-th leading minor not positive definite

During handling of the above exception, another exception occurred:

LinAlgError                               Traceback (most recent call last)
/Users/elancheliyan/anaconda/lib/python3.5/site-packages/sklearn/mixture/gmm.py in _log_multivariate_normal_density_full(X, means, covars, min_covar)
    706                 cv_chol = linalg.cholesky(cv + min_covar * np.eye(n_dim),
--> 707                                           lower=True)
    708             except linalg.LinAlgError:

/Users/elancheliyan/anaconda/lib/python3.5/site-packages/scipy/linalg/decomp_cholesky.py in cholesky(a, lower, overwrite_a, check_finite)
     80     c, lower = _cholesky(a, lower=lower, overwrite_a=overwrite_a, clean=True,
---> 81                             check_finite=check_finite)
     82     return c

/Users/elancheliyan/anaconda/lib/python3.5/site-packages/scipy/linalg/decomp_cholesky.py in _cholesky(a, lower, overwrite_a, clean, check_finite)
     29     if info > 0:
---> 30         raise LinAlgError("%d-th leading minor not positive definite" % info)
     31     if info < 0:

LinAlgError: 3-th leading minor not positive definite

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-61-1556fc08e0e0> in <module>()
      3     model.transmat_ = np.ones((n, n)) / n
      4     model.startprob_ = np.ones(n) / n
----> 5     fit = model.fit(i.T)
      6     z=fit.decode(data_split,algorithm = 'viterbi')[1]
      7     states.append(z)

/Users/elancheliyan/anaconda/lib/python3.5/site-packages/hmmlearn-0.2.1-py3.5-macosx-10.5-x86_64.egg/hmmlearn/base.py in fit(self, X, lengths)
    427             curr_logprob = 0
    428             for i, j in iter_from_X_lengths(X, lengths):
--> 429                 framelogprob = self._compute_log_likelihood(X[i:j])
    430                 logprob, fwdlattice = self._do_forward_pass(framelogprob)
    431                 curr_logprob += logprob

/Users/elancheliyan/anaconda/lib/python3.5/site-packages/hmmlearn-0.2.1-py3.5-macosx-10.5-x86_64.egg/hmmlearn/hmm.py in _compute_log_likelihood(self, X)
    198     def _compute_log_likelihood(self, X):
    199         return log_multivariate_normal_density(
--> 200             X, self.means_, self._covars_, self.covariance_type)
    201
    202     def _generate_sample_from_state(self, state, random_state=None):

/Users/elancheliyan/anaconda/lib/python3.5/site-packages/sklearn/mixture/gmm.py in log_multivariate_normal_density(X, means, covars, covariance_type)
     63         'full': _log_multivariate_normal_density_full}
     64     return log_multivariate_normal_density_dict[covariance_type](
---> 65         X, means, covars)
     66
     67

/Users/elancheliyan/anaconda/lib/python3.5/site-packages/sklearn/mixture/gmm.py in _log_multivariate_normal_density_full(X, means, covars, min_covar)
    707                                           lower=True)
    708             except linalg.LinAlgError:
--> 709                 raise ValueError("'covars' must be symmetric, "
    710                                  "positive-definite")
    711

ValueError: 'covars' must be symmetric, positive-definite
```
Am I doing it right way ?

**Comment by epratheeban** [comment] 2016-07-11 12:04
After updating the version. 

```
In [5]: run tryhmm.py
/Users/elancheliyan/anaconda/bin/python.app: line 3:  5286 Killed: 9               /Users/elancheliyan/anaconda/python.app/Contents/MacOS/python "$@"
```

I got this error  and it exited from the Ipython. I also reduced the number of states per speaker to 30 (N = 300).

**Comment by superbobry** [comment] 2016-07-12 08:37
You need at least as many observations as the dimensionality of `X` to estimate the covariance matrix, thus the `ValueError` above. 

As for the exit, it seems like an out-of-memory issue, but I can't be sure without reproducing it locally. Could you attach a sample of the the data you're using to the issue?

**Comment by epratheeban** [comment] 2016-07-12 09:38
@superbobry  : The data is here in the bitbucket repo [data.dat](https://bitbucket.org/pratheeban/public_files/src/b8907bb4b56364fb48c9a711153531c146c16758/MFCC/?at=master).

So what should I do to correct the ValueError ?

**Comment by superbobry** [comment] 2016-07-12 10:14
> So what should I do to correct the ValueError?

Ensure the training sample is large enough.

Could you also add the source of `tryhmm.py`?

**Comment by epratheeban** [comment] 2016-07-12 10:34
@superbobry  Here  the  [tryhmm.py](https://bitbucket.org/pratheeban/public_files/src/3d3b2ded3fc624e47f14aaf9bb430e0ea0eb1b35/MFCC/tryhmm.py?at=master&fileviewer=file-view-default). 

I will look at the training sample.

**Comment by epratheeban** [comment] 2016-07-12 10:52
@superbobry  Please note that , In the given code tryhmm.py. I used `covariance_type="diag"` but previously I tried with `covariance_type="full"`.

**Comment by superbobry** [comment] 2016-07-13 15:58
Unfortunately, I wasn't able to reproduce the problem locally. `tryhmm.py` successfully fitted a model multiple times. Peak memory usage was ~1.6G.

Could you try running `tryhmm.py` outside IPython?

**Comment by epratheeban** [comment] 2016-07-15 09:30
Yes I tried after running outside IPython. Again I got the same error. I think, my machine is not fit to do such heavy computation. I try to run on some other machine and post you the results. 

Did you changed anything in the code ? If so please let me know.

**Comment by epratheeban** [comment] 2016-08-08 14:20
@superbobry  Thank you. I successfully ran the code and found the probable states. The only thing is, it took 18 hours to do the computation. You can close the issue now.

**Comment by superbobry** [comment] 2016-08-09 13:40
Cool! I could parallelize fitting over input sequences, would you be interested in trying this out?

**Comment by epratheeban** [comment] 2016-08-09 14:09
@superbobry  That would be awesome ! Please tell me how to do that.

**Comment by epratheeban** [comment] 2016-10-05 15:33
Hello @superbobry , 
Is there any update about parallelize fitting over input sequence? It will be helpful save to some time in my computation.

**Comment by superbobry** [comment] 2016-10-10 22:06
Hi @epratheeban! Sorry, I've been busy with other projects lately. 

The base HMM is indeed ready for || fitting. The only thing required is to replace the forloop [here](https://github.com/hmmlearn/hmmlearn/blob/master/hmmlearn/base.py#L431) with a thread pool-backed `joblib.Parallel` call. However, there is another issue which needs to be resolved for you to be able to benefit from ||: the new version of GMMHMM (see #107) still needs some more testing and brooming.

**Comment by GavinF17** [comment] 2017-01-24 12:19
HI @epratheeban, I believe I'm having the same issues you were having which you seem to have fixed by running it on a different machine. Are you able to give any details on how the machines differed so that I can look into what I need to change to see if I can get the same "fix"?

**Comment by epratheeban** [comment] 2017-05-11 15:12
@GavinF17 I ran the code in a cluster which has 24 cores and 100 GB ram. Sorry for the delay. I moved to bitbucket for a while. Do you have any other question ?

**Closed** 2018-09-28 13:12 UTC
