### ISSUE TITLE
error running 'plot_hmm_stock_analysis.py'

### ISSUE THREAD

**Issue by shirisimon** [hmmlearn/hmmlearn#53] opened 2015-10-14 08:57 UTC
I get the following error when running 'plot_hmm_stock_analysis.py' under Windows 10 with Anaconda 2.3.0 (64-bit)| (default, Dec 18 2014):

` hmmlearn\utils.py:61: RuntimeWarning: invalid value encountered in subtract
  out = np.log(exp_mask_zero(a - a_max).sum(axis=0))
C:\Users\Shiri\myndlift\GIT\python_learn_muse_weights_from_cz\hmmlearn\hmm.py:258: RuntimeWarning: invalid value encountered in maximum
  self._covars_ = (covars_prior + cv_num) / np.maximum(cv_den, 1e-5)`

`Traceback (most recent call last):
  File "C:/Users/Shiri/myndlift/GIT/python_learn_muse_weights_from_cz/hmm_example.py", line 55, in <module>
    hidden_states = model.predict(X)
  File "C:\Users\Shiri\myndlift\GIT\python_learn_muse_weights_from_cz\hmmlearn\base.py", line 317, in predict
    _, state_sequence = self.decode(X, lengths)
  File "C:\Users\Shiri\myndlift\GIT\python_learn_muse_weights_from_cz\hmmlearn\base.py", line 278, in decode
    self._check()
  File "C:\Users\Shiri\myndlift\GIT\python_learn_muse_weights_from_cz\hmmlearn\hmm.py", line 155, in _check
    super(GaussianHMM, self)._check()
  File "C:\Users\Shiri\myndlift\GIT\python_learn_muse_weights_from_cz\hmmlearn\base.py", line 479, in _check
    .format(self.startprob_.sum()))
ValueError: startprob_ must sum to 1.0 (got nan) `

**Comment by superbobry** [comment] 2015-10-14 15:55
Hello @shirisimon, are you using the `master` version of `hmmlearn`?

**Comment by shirisimon** [comment] 2015-10-14 16:09
Yes. I cloned the hmmlearn repository earlier today with 'https://github.com/hmmlearn/hmmlearn.git'

**Comment by superbobry** [comment] 2015-10-14 17:31
I've been trying to nail this underflow issue for quite some time without much success. Can you please add which versions of Python, NumPy and SciPy you're using?

**Comment by shirisimon** [comment] 2015-10-15 09:26
HERE: 
Python version:     2.7.9
IPython version:       3.2.0
Numpy version:         1.9.2
SciPy version:        0.15.1

**Comment by superbobry** [comment] 2015-12-17 08:52
Hi @shirisimon. Can you please try the `master` version of `hmmlearn` and check if the issue is still there?

**Comment by shirisimon** [comment] 2015-12-22 07:32
Hi Sergei,

I am now having the following import error:
Traceback (most recent call last):
  File
"/home/shiri/Desktop/myndlift/gitrepo/CzPrediction_python/hmmlearn-master/examples/plot_hmm_stock_analysis.py",
line 25, in <module>
    from hmmlearn.hmm import GaussianHMM
  File
"/home/shiri/Desktop/myndlift/gitrepo/CzPrediction_python/hmmlearn-master/hmmlearn/hmm.py",
line 21, in <module>
    from .base import _BaseHMM
  File
"/home/shiri/Desktop/myndlift/gitrepo/CzPrediction_python/hmmlearn-master/hmmlearn/base.py",
line 13, in <module>
    from . import _hmmc
ImportError: cannot import name _hmmc

Shiri



On Thu, Dec 17, 2015 at 10:52 AM, Sergei Lebedev <notifications@github.com>
wrote:

> Hi @shirisimon <https://github.com/shirisimon>. Can you please try the
> master version of hmmlearn and check if the issue is still there?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hmmlearn/hmmlearn/issues/53#issuecomment-165386611>.
>



-- 
Shiri Simon PhD Candidate
Motor Cognition Lab
The Interdisciplinary Doctoral Program in Neuroscience

Sagol School of Neuroscience

The School for Psychological Sciences

Tel Aviv University

Ramat Aviv, Tel Aviv 69978, Israel

**Comment by superbobry** [comment] 2016-01-05 02:48
I think you could've forgotten to build the extension. Can you do

```
$ python setup.py build_ext --inplace
```

and try again?

**Comment by superbobry** [comment] 2016-01-13 17:28
I've failed to reproduce the issue with the latest `hmmlearn` and Anaconda 2.3.0 on Windows 7, so closing as *fixed*.

**Closed by superbobry** 2016-01-13 17:28 UTC
